
- name: set build folder
  set_fact: build={{ project_install_path }}/{{ ansible_date_time.epoch }}

- name: create build folder
  file: path={{ build }} state=directory mode=0755
        owner={{ project_user }} group={{ project_user }}
  become: yes

- name: download project from repo (w/key)
  git: repo={{ project_repo }} dest={{ build }} clone=yes
       key_file={{ project_deploy_key }}
  when: project_use_deploy_key

- name: download project from repo (no key)
  git: repo={{ project_repo }} dest={{ build }} clone=yes
  when: not project_use_deploy_key

- name: copy settings.py file
  copy: src={{ project_settings_file }}
        dest={{ build }}/{{ project_settings_relative_dest }}
        mode=0600 owner={{ project_user }} group={{ project_user }}
  when: project_settings_file is string

- name: create settings.py file from template
  template: src={{ project_settings_template }}
            dest={{ build }}/{{ project_settings_relative_dest }}
            mode=0600 owner={{ project_user }} group={{ project_user }}
  when: project_settings_template is string

- name: find requirements.txt
  stat: path={{ build }}/requirements.txt
  register: reqmts

- name: install requirements in venv
  pip: requirements={{ build }}/requirements.txt executable={{ virtualenv_pip }}
  when: reqmts.stat.exists == True
  register: pip_result
  changed_when: "'Successfully installed' in pip_result.stdout"

- name: run tests
  command: "{{ project_test_cmd }} chdir={{ build }}"

- name: create symlink to new build
  file: src={{ build }} dest={{ project_install_path }}/current state=link
  become: yes
